version: '3'
name: testparser
services:
    fpm:
        build: ./fpm
        tty: true
        working_dir: /var/www/testparser
        volumes:
            - ../.:/var/www/testparser:cached
            - ./fpm/config/php.ini-local:/usr/local/etc/php/php.ini
            
    nginx:
        image: nginx:stable-alpine
        working_dir: /var/www/testparser
        ports:
            - "80:80"
        volumes:
            - ../.:/var/www/testparser:cached
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated

    mysql:
        platform: linux/x86_64
        image: mysql:8.0
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=testparserDB
            - MYSQL_PASSWORD=secret
        ports:
            - "3306:3306"
volumes:
    mysql_data:
